package youtube;

public enum RequestTypes {
    // users
    GET_USERINFO,
    SIGN_IN,
    FOLLOW,
    UNFOLLOW,
    SET_USER_PROFILE_PHOTO,
    SET_USER_CHANNEL_PHOTO,
    EDIT_USER,
    CREATE_USER,
    DELETE_USER,

    // videos
    GET_VIDEO_BY_ID,
    GET_USER_VIDEOS,
    GET_NEW_VIDEOS,
    GET_TRENDING_VIDEOS_OF_SUBSCRIPTIONS,
    GET_TRENDING_VIDEOS,
    GET_RELATED_VIDEOS,
    GET_VIDEOS_OF_TAG,
    CREATE_VIDEO,
    SET_VIDEO_VISIBILITY,
    SET_VIDEO_THUMBNAIL,
    EDIT_VIDEO,
    DELETE_VIDEO,
    PUT_VIDEO_LIKE,
    DELETE_VIDEO_LIKE,
    PUT_VIDEO_TAG,
    DELETE_VIDEO_TAG,

    // playlists
    GET_PLAYLIST_ID,
    GET_PLAYLIST,
    CREATE_PLAYLIST,
    SET_PLAYLIST_THUMBNAIL,
    EDIT_PLAYLIST,
    DELETE_PLAYLIST,
    PUT_ADMIN_PLAYLIST,
    DELETE_ADMIN_PLAYLIST,
    PUT_VIDEO_PLAYLIST,
    EDIT_VIDEO_PLAYLIST,
    DELETE_VIDEO_PLAYLIST,
    GET_PLAYLIST_VIDEOS,
    GET_USER_PLAYLIST,

    // comments
    GET_COMMENTS_OF_VIDEO,
    GET_REPLIES_OF_COMMENT,
    CREATE_COMMENT,
    EDIT_COMMENT,
    DELETE_COMMENT,
    PUT_COMMENT_LIKE,
    DELETE_COMMENT_LIKE,

    // histories
    GET_HISTORIES,
    DELETE_HISTORY,
    DELETE_ALL_USER_HISTORY,

    // notifications
    GET_UNSEEN_NOTIFICATION_COUNT,
    GET_UNSEEN_NOTIFICATIONS,
    SET_NOTIFICATION_SEEN,
    SET_ALL_NOTIFICATION_SEEN,
    DELETE_NOTIFICATION,
    DELETE_ALL_NOTIFICATION,

    // photo and video
    GET_PHOTO,
    GET_VIDEO,
}
