package youtube.server.migration;

public class M02_videos implements MigrationInterface {
    @Override
    public String getCreateQuery() {
        return """
           CREATE TABLE IF NOT EXISTS videos (
               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
               title VARCHAR(128) NOT NULL,
               description VARCHAR(1024) NULL,
               path_url VARCHAR(16) NOT NULL UNIQUE,
               user_id BIGINT NOT NULL,
               created_at TIMESTAMP NOT NULL DEFAULT NOW(),
               updated_at TIMESTAMP NULL,
               thumbnail BYTEA NULL,
               FOREIGN KEY ("user_id") REFERENCES "users" ("id")
           );       
        """;
    }

    @Override
    public String getDropQuery() {
        return "DROP TABLE IF NOT EXISTS videos;";
    }
}
