package youtube.server.migration;

public class M10_playlistVideos implements MigrationInterface {
    @Override
    public String getCreateQuery() {
        return """
            CREATE TABLE IF NOT EXISTS playlist_videos (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                playlist_id BIGINT NOT NULL,
                video_id BIGINT NOT NULL,
                custom_order INT NOT NULL DEFAULT 1,
                created_at TIMESTAMP NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMP NULL,
                -- UNIQUE(playlist_id,video_id,custom_order),
                FOREIGN KEY (video_id) REFERENCES videos (id) ON DELETE CASCADE
            );
        """;
    }

    @Override
    public String getDropQuery() {
        return "DROP TABLE IF NOT EXISTS playlist_videos;\n";
    }
}
