package youtube.server.database.migration;

public class M03_likes implements MigrationInterface {
    @Override
    public String getCreateQuery() {
        return """
            CREATE TABLE IF NOT EXISTS likes (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                is_like BOOLEAN NOT NULL DEFAULT TRUE,
                user_id BIGINT NOT NULL,
                video_id BIGINT NOT NULL,
                created_at TIMESTAMP NOT NULL DEFAULT NOW(),
                FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
                FOREIGN KEY (video_id) REFERENCES videos (id) ON DELETE CASCADE,
                UNIQUE (user_id,video_id)
            );
        """;
    }

    @Override
    public String getDropQuery() {
        return "DROP TABLE IF EXISTS likes;";
    }
}
