package youtube.server.database.migration;

public class M05_commentsLikes implements MigrationInterface {

    @Override
    public String getCreateQuery() {
        return """
            CREATE TABLE IF NOT EXISTS comments_likes (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                is_like BOOLEAN NOT NULL DEFAULT TRUE,
                user_id BIGINT NOT NULL,
                comment_id BIGINT NOT NULL,
                created_at TIMESTAMP NOT NULL DEFAULT NOW(),
                FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
                FOREIGN KEY (comment_id) REFERENCES comments (id) ON DELETE CASCADE,
                UNIQUE (user_id,comment_id)
            );
        """;
    }

    @Override
    public String getDropQuery() {
        return "DROP TABLE IF EXISTS comments_likes;";
    }
}
