package youtube.server.database.migration;

public class M07_videoTags implements MigrationInterface {
    @Override
    public String getCreateQuery() {
        return """
            CREATE TABLE IF NOT EXISTS video_tags (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                video_id BIGINT NOT NULL,
                tag_id BIGINT NOT NULL,
                created_at TIMESTAMP NOT NULL DEFAULT NOW(),
                FOREIGN KEY (video_id) REFERENCES videos (id) ON DELETE CASCADE,
                FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE CASCADE,
                UNIQUE(video_id,tag_id)
            );
        """;
    }

    @Override
    public String getDropQuery() {
        return "DROP TABLE IF EXISTS video_tags;";
    }
}
