package youtube.server.database.migration;

public class M11_playlistVideos implements MigrationInterface {
    @Override
    public String getCreateQuery() {
        return """
            CREATE TABLE IF NOT EXISTS playlist_videos (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                playlist_id BIGINT NOT NULL,
                admin_id BIGINT NOT NULL ,
                video_id BIGINT NOT NULL,
                custom_order INT NOT NULL DEFAULT 1,
                created_at TIMESTAMP NOT NULL DEFAULT NOW(),
                FOREIGN KEY (video_id) REFERENCES videos (id) ON DELETE CASCADE,
                FOREIGN KEY (playlist_id) REFERENCES playlists (id) ON DELETE CASCADE,
                FOREIGN KEY (admin_id) REFERENCES playlist_admins (id) ON DELETE CASCADE,
                UNIQUE(playlist_id,video_id)
            );
        """;
    }

    @Override
    public String getDropQuery() {
        return "DROP TABLE IF EXISTS playlist_videos;\n";
    }
}
