package youtube.server.database.migration;

public class M13_notifications  implements MigrationInterface {
    @Override
    public String getCreateQuery() {
        return """
            CREATE TABLE IF NOT EXISTS notifications (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                owner_user_id BIGINT NULL,
                message VARCHAR(128) NOT NULL,
                notification_type INT NOT NULL,
                user_id BIGINT NULL,
                video_id BIGINT NULL,
                comment_id BIGINT NULL,
                playlist_id BIGINT NULL,
                is_like BOOLEAN DEFAULT TRUE,
                seen BOOLEAN DEFAULT FALSE,
                created_at TIMESTAMP NOT NULL DEFAULT NOW(),
                FOREIGN KEY (owner_user_id) REFERENCES users (id) ON DELETE CASCADE,
                FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
                FOREIGN KEY (video_id) REFERENCES videos (id) ON DELETE CASCADE,
                FOREIGN KEY (comment_id) REFERENCES comments (id) ON DELETE CASCADE,
                FOREIGN KEY (playlist_id) REFERENCES playlists (id) ON DELETE CASCADE
            );
        """;
    }

    @Override
    public String getDropQuery() {
        return "DROP TABLE IF EXISTS notifications;";
    }
}